---
plugins:
  - cypress

extends:
  - airbnb
  - "plugin:react/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  cypress/globals: true

rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-console: 0
  react/prop-types: 0
