---

extends:
  - airbnb
  # - "plugin:jest/recommended"
  - "plugin:react/recommended"
  # - "jest-enzyme"

parser: babel-eslint

env:
  browser: true
  node: true
  # jest: true

rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-console: 0
  no-useless-constructor: 0
  react/prop-types: 0
